[package]
name = "bitbot-rs"
version = "0.1.0"
authors = ["Daniel Bluhm <bluhmdan@gmail.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11.24"
hyper-tls = "0.1.3"
tokio-core = "0.1"
failure = "0.1.1"
failure_derive = "0.1.1"
serde_json = "1.0.13"
toml = "0.4.5"
